### ISSUE TITLE
GUIWrapper not opening on Windows Server 2019

### ISSUE THREAD

**Issue by yannickboy15** [frodal/GUIwrapper#14]
Hi there,

I've installed your application from the installer exe, but it's not showing up. I see the process in my Task Manager, but nothing else shows up. Got a clue what it might be?

**Comment by frodal** [comment]
Have you tried running the application using either the GUIwrapper-win32-x64.zip or GUIwrapper-win32-ia32.zip? 
I think this problem might be related to this issue: https://github.com/electron/electron/issues/26675
It appears to be working with electron 9, you could try to build the application using electron 9 and see if that changes anything.

**Comment by yannickboy15** [comment]
I pulled my fork, npm installed and npm started. That worked fine somehow. I'll try the other ZIPs later, writing now a contribution for multiple process support :)

**Comment by yannickboy15** [comment]
Do you have possibly Skype, Discord or another way to communicate one to one? Got several questions you might have an answer to.

**Comment by frodal** [comment]
Yes, we could talk on Discord: Bjynne#5670

**Comment by promatik** [comment]
Hi everyone, I saw you tagged my issue on electron, about the blank screen on windows server.

I don't even know what this repo is, but I'm stepping by to let you know that **v11.3.0** solved the problem for me.
So I recommend you to update your dependencies and rebuild your app 🙌

**Comment by frodal** [comment]
Thanks for your feedback @promatik 🥇
